on:
    workflow_dispatch:
  
jobs:
  propose_translation:
    uses: openvoiceos/.github/.github/workflows/auto_translate.yml@feat/shared_actions1
    with:
      branch: dev
      python_version: '"3.8"'
      locale_folder: ovos_testpkg/locale/