name: Parse PR Title (Conventional Commits)
on:
  pull_request:
    branches:
      - dev
      - staging*
      - testing

jobs:
  license_tests:
    uses: openvoiceos/.github/.github/workflows/check_conventional_commits.yml@feat/shared_actions1
    secrets: inherit