name: Status Check (Labelling conventional commits and testing phase)
on:
  schedule:
    - cron:  '0 6 * * *'

  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - dev
      - staging*

# triggered by pull request will only check against the pull request
# triggered on schedule will check all open pull requests
jobs:
  status_check:
    uses: openvoiceos/.github/.github/workflows/check_conventional_commits.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: feat/shared_actions1 
      pr_number: ${{ github.event.pull_request.number || null }}