name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    if: github.actor != 'EggmanBot'
    uses: openvoiceos/.github/.github/workflows/check_conventional_commits.yml@feat/shared_actions1
    secrets: inherit    
