name: License testing
on:
  push:
    branches:
      - stable
      - testing
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  license_tests:
    uses: openvoiceos/.github/.github/workflows/license_tests.yml@feat/shared_actions1
    with:
      runner: ubuntu-latest
      action_branch: feat/shared_actions1
      python-version: "3.10"