name: Propose SemVer Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - "build"
          - "minor"
          - "major"

jobs:
  build_and_publish:
    uses: openvoiceos/.github/.github/workflows/propose_semver_release.yml@feat/shared_actions1
    with:
      branch: dev
      action_branch: feat/shared_actions1
      python_version: "3.10"
      version_file: ovos_testpkg/version.py
      release_type: ${{ inputs.release_type }}