name: Propose Translations
on:
  workflow_dispatch:
    inputs:
      translation:
        type: choice
        options:
          - bg-BG
          - cs-CZ
          - da-DK
          - de-DE
          - el-GR
          - en-GB
          - en-US
          - es-ES
          - et-EE
          - fi-FI
          - fr-FR
          - hu-HU
          - id-ID
          - it-IT
          - ja-JP
          - ko-KR
          - lt-LT
          - lv-LV
          - nb-NO
          - nl-NL
          - pl-PL
          - pt-BR
          - pt-PT
          - ro-RO
          - ru-RU
          - sk-SK
          - sl-SI
          - sv-SE
          - tr-TR
          - uk-UA
          - zh-CN

jobs:
  propose_translation:
    uses: openvoiceos/.github/.github/workflows/propose_translation.yml@feat/shared_actions1
    with:
      branch: dev
      action_branch: feat/shared_actions1
      python_version: "3.10"
      language: ${{ inputs.translation }}
      locale_folder: ovos_testpkg/locale/
      reviewers: "jarbasai,emphasize"