name: Rebase dev after review

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - testing
      - stable

jobs:
  release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.commit.message, 'patch release') || contains(github.event.pull_request.head.commit.message, 'minor release') || contains(github.event.pull_request.head.commit.message, 'major release')
    uses: openvoiceos/.github/.github/workflows/propose_semver_release_merged.yml@feat/shared_actions1
    secrets: inherit
