name: Publish Alpha Build ...aX
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovos_testpkg/version.py'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: openvoiceos/.github/.github/workflows/publish_alpha_release.yml@feat/shared_actions1
    secrets: inherit
    with:
      branch: dev
      version_file: ovos_testpkg/version.py
      python_version: "3.10"
      locale_folder: ovos_core/locale
