name: Publish Alpha Build
on:
  workflow_dispatch:

jobs:
  build_and_publish:
    uses: openvoiceos/.github/.github/workflows/release_alpha.yml@feat/shared_actions1
    secrets: inherit
    with:
      branch: dev
      action_branch: feat/shared_actions1
      version_file: ovos_testpkg/version.py
      python_version: "3.10"
      locale_folder: ovos_testpkg/locale
      update_intentfile: test/unittests/test_intent.yaml
