name: Publish SemVer Build
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  build_and_publish:
    uses: openvoiceos/.github/.github/workflows/publish_semver_release.yml@feat/shared_actions1
    secrets: inherit
    with:
      python_version: "3.10"
      release_type: ${{ inputs.release_type }}
