name: Synchronize testing branch with dev
on:
  workflow_dispatch:

jobs:
  propose_translation:
    uses: openvoiceos/.github/.github/workflows/release_synchronize_testing.yml@feat/shared_actions1
    secrets: inherit