name: Start Testing Phase
# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - testing

jobs:
  start_testing_phase:
    if: >
      github.event.pull_request.merged == true &&
      github.actor != 'EggmanBot' &&
      (contains(github.event.pull_request.title, 'patch release') ||
      contains(github.event.pull_request.title, 'minor release') ||
      contains(github.event.pull_request.title, 'major release'))
    uses: openvoiceos/.github/.github/workflows/release_semver_versioning.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: feat/shared_actions1
      version_file: ovos_testpkg/version.py
      subject: ${{ github.event.pull_request.title }}
