name: Start Testing Phase
# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - testing
      - dev

jobs:
  start_testing_phase:
    if: github.actor != 'EggmanBot' && github.event.pull_request.merged == true && contains(fromJson('["patch release", "minor release", "major release"]'), github.event.pull_request.title)
    uses: openvoiceos/.github/.github/workflows/release_semver_versioning.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: feat/shared_actions1
      version_file: ovos_testpkg/version.py
      subject: ${{ github.event.pull_request.title }}