name: Start Testing Phase
# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches:
      - testing
      - dev

jobs:
  start_testing_phase:
    runs-on: ubuntu-latest
    steps:
      - name: Debug actor
        run: |
          echo "Actor: ${{ github.actor }}"
      - name: Debug merged status
        run: |
          echo "Merged: ${{ github.event.pull_request.merged }}"
      - name: Debug PR title
        run: |
          echo "Title: ${{ github.event.pull_request.title }}"