name: Start release mechanism
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - "alpha"
          - "patch"
          - "minor"
          - "major"
      kickoff_pr:
        type: choice
        options:
          - "true"
          - "false"
  # Make SURE that sqashed PRs do have the PRs title as commit message !!!!!!!!
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovos_testpkg/version.py'
      - 'test/**'
      - 'examples/**'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'scripts/**'

jobs:
  start_semver_release_mechanism:
    if: github.actor != 'EggmanBot'
    uses: openvoiceos/.github/.github/workflows/release_semver_start.yml@feat/shared_actions1
    with:
      branch: dev                                                  # Branch to use, default: branch that triggered the action
      action_branch: feat/shared_actions1                          # Shared action branch to use, default: main
      python_version: "3.10"                                       # the python version to use
      version_file: "ovos_testpkg/version.py"                      # the file containing the version number
      locale_folder: ovos_testpkg/locale                           # the location of the base localisation folder
      update_intentfile: test/unittests/test_intent.yaml           # the intent file resources gets tested against
      release_type: ${{ inputs.release_type || null }}             # if manually triggered, set a release type
      subject: ${{  github.event.head_commit.message || null }}    # on push, the commit message is used as release subject
      kickoff_pr: ${{ fromJson( inputs.kickoff_pr || 'true' ) }}   # if the release process should be started with a PR to summarize and visualize, default: false

