name: Propose SemVer Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        options:
          - "alpha"
          - "patch"
          - "minor"
          - "major"
  # Make SURE that sqashed PRs do have the PRs title as commit message !!!!!!!!
  push:
    branches:
      - dev
    paths-ignore:
      - 'ovos_testpkg/version.py'
      - 'test/**'
      - 'examples/**'
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'scripts/**'

jobs:
  start_semver_release_mechanism:
    uses: openvoiceos/.github/.github/workflows/release_semver_start.yml@feat/shared_actions1
    secrets: inherit
    with:
      branch: dev
      action_branch: feat/shared_actions1
      python_version: "3.10"
      version_file: "ovos_testpkg/version.py"
      locale_folder: ovos_testpkg/locale
      update_intentfile: test/unittests/test_intent.yaml
      release_type: ${{ inputs.release_type || null }}
      subject: ${{  github.event.head_commit.message || null }}
      kickoff_pr: true
