name: Skill Tests
on:
  push:
    branches:
      - testing
      - stable
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'ovos_testpkg/version.py'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  skill_install_test:
    uses: openvoiceos/.github/.github/workflows/skill_test_installation.yml@feat/shared_actions1
    with:
      skill_id: ovos-testpkg.openvoiceos
      skill_location: ovos_testpkg
  skill_intent_test:
    uses: openvoiceos/.github/.github/workflows/skill_test_intents.yml@feat/shared_actions1
    with:
      skill_id: ovos-testpkg.openvoiceos
      intent_testfile: test/unittests/test_intents.yaml
      test_padatious: true
  skill_resource_test:
    uses: openvoiceos/.github/.github/workflows/skill_test_resources.yml@feat/shared_actions1
    with:
      skill_id: ovos-testpkg.openvoiceos
      resource_testfile: test/unittests/test_resources.yaml
  skill_tests:
    uses: openvoiceos/.github/.github/workflows/skill_tests.yml@feat/shared_actions1
    with:
      skill_testfile: test/unittest/test_skill.py