name: Skill Tests
on:
  pull_request:
    branches:
      - dev
      - staging*
      - testing
      - master
    # remove setup.py after testing
    paths-ignore:
      - 'ovos_testpkg/version.py'
      - 'ovos_testpkg/locale/**'
      - 'test/**'
      - 'examples/**'
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'MANIFEST.in'
      - 'README.md'
      - 'scripts/**'
      - 'setup.py'
  workflow_dispatch:

jobs:
  skill_install_test:
    if: github.actor != 'EggmanBot'
    uses: openvoiceos/.github/.github/workflows/skill_test_installation.yml@feat/shared_actions1
    with:
      action_branch: feat/shared_actions1
      skill_id: ovos-testpkg.openvoiceos
      skill_location: ovos_testpkg
      
  skill_resource_test:
    if: github.actor != 'EggmanBot'
    uses: openvoiceos/.github/.github/workflows/skill_test_resources.yml@feat/shared_actions1
    with:
      action_branch: feat/shared_actions1
      intent_testfile: test/unittests/test_intents.yaml

  skill_tests:
    if: github.actor != 'EggmanBot'
    uses: openvoiceos/.github/.github/workflows/pytest_file_or_dir.yml@feat/shared_actions1
    secrets: inherit
    with:
      action_branch: feat/shared_actions1
      test_location: test/unittests/test_skill.py
      is_skill: true
